export const myCaptions = [
  "Emperor Severus oppresses the Roman Senate and elevates the Praetorian Guard (197 AD)",
  "The profligate luxury of Elagabalus and marriage to a Vestal Virgin (219 AD)",
  "The tremendous stature the usurper Maximin, overcoming Emperor Alexander Severus (235 AD)",
  "Defeat and death of the two Gordians, father and son, by the usurper Maximin (238 AD)",
  "The defeat and death of Emperor Decius and his son, slain by an arrow, and his father beneath a morass, by the Goths in Maesia (251 AD)",
  "The Gothic Nation increases it's numbers while marching to the Danube, preparing for war against the Roman Empire (251 AD)",
  "The Goths acquire a naval force, and sail the Euxine in floating houses with their woman and children, to attack the Roman Empire (260 AD)",
];

export const aiCaptions = [
  "The reign of Augustus establishes a long period of relative peace known as the Pax Romana (27 BC - 14 AD)",
  "The reign of Tiberius marked by increasing autocracy and the rise of the Praetorian Guard (14-37 AD)",
  "Caligula's eccentric and tyrannical rule, characterized by lavish spending and cruel punishments (37-41 AD)",
  "The principled reign of Claudius and expansion of the Roman Empire, including the conquest of Britain (41-54 AD)",
  "Nero's infamous rule, marked by extravagance, the Great Fire of Rome, and persecution of Christians (54-68 AD)",
  "The Year of the Four Emperors, a chaotic period of civil war and political instability (69 AD)",
  "The Flavian Dynasty, under Vespasian, Titus, and Domitian, known for military success and the completion of the Colosseum (69-96 AD)",
  "The 'Five Good Emperors' era, a period of prosperity and relative peace under Nerva, Trajan, Hadrian, Antoninus Pius, and Marcus Aurelius (96-180 AD)",
  "The Antonine Plague, a devastating epidemic that significantly impacted the Roman Empire (165-180 AD)",
  "Commodus' erratic and self-indulgent rule, marking the beginning of the Empire's decline (180-192 AD)",
  "The Visigothic Kingdom flourishes in Spain under King Euric, expanding its territory and consolidating power (late 5th century AD)",
  "The reign of Emperor Zeno and the growing influence of barbarian generals in the Eastern Roman Empire (474-491 AD)",
  "The Ostrogothic King Theodoric the Great becomes the ruler of Italy, establishing a kingdom and fostering a period of stability and cultural achievement (493-526 AD)",
  "The Franks under King Clovis conquer Gaul, laying the foundation for the Merovingian dynasty and the Frankish Empire (late 5th century AD)",
  "The rise of the Vandal kingdom in North Africa under King Genseric, posing a significant threat to the Roman Empire (5th century AD)",
  "Emperor Anastasius I reforms the fiscal system of the Eastern Roman Empire, leading to economic prosperity (491-518 AD)",
  "The conflict between the Monophysite and Chalcedonian Christian doctrines creates deep religious divisions within the Eastern Roman Empire (5th-6th century AD)",
  "Justinian's Code is compiled, a monumental work of legal codification that forms the basis of Byzantine law (529 AD)",
  "The devastating effects of the Plague of Justinian on the Byzantine Empire, causing widespread death and economic turmoil (541-542 AD)",
  "The Lombards invade Italy, further fragmenting the former Western Roman Empire and establishing a kingdom in the Italian Peninsula (568 AD)",
  "Constantius II, cloaked in imperial garb, presides over a council, his face reflecting the burden of religious and political strife tearing at the fabric of the empire (337-361 AD)",
  "Julian the Apostate, in philosopher's robes, fervently performs a pagan ritual, attempting to revive ancient Roman gods amidst the ruins of a temple (361-363 AD)",
  "Valentinian I and Valens, each on a throne, facing away from each other to symbolize the division of the empire, with scenes of conflict and dissent surrounding them (364-375 AD)",
  "Gratian, young and resolute, stands with a scepter in hand, amidst advisors and soldiers, portraying his struggle to unite the empire under his rule (375-383 AD)",
  "Magnentius, a figure of defiance, clad in battle armor, confronts Constantius II in a dramatic scene of civil war and conflict (350-353 AD)",
  "Theodosius I, solemn and majestic, depicted at the moment of declaring Christianity as the state religion, with a diverse crowd reacting variously with joy and dismay (379-395 AD)",
  "The Gothic War depicted vividly: Roman legions clashing with Gothic warriors, emphasizing the chaos and desperation of this significant conflict (376-382 AD)",
  "The anguished scene of the massacre of Thessalonica, with Theodosius I in the foreground, his face a portrait of regret and penance (390 AD)",
  "The sons of Theodosius, Arcadius and Honorius, shown receiving the halves of the empire, a visual metaphor of the splitting of the Roman world (395 AD)",
  "A dramatic encounter between Stilicho and Alaric, the former in Roman military attire, the latter in Gothic gear, under a sky filled with foreboding clouds, symbolizing the brewing storm (early 5th century AD)",
  "The dramatic scene of Emperor Honorius receiving news of the sack of Rome, portrayed in his palace, surrounded by advisors, his face reflecting shock and disbelief (410 AD)",
  "The meeting of Attila the Hun and Pope Leo I, a tense yet majestic tableau, with Attila on horseback and the Pope standing firm, embodying a clash of civilizations (452 AD)",
  "The deposition of Romulus Augustulus, the last Roman Emperor, by Odoacer; a poignant scene showing the young emperor relinquishing the crown (476 AD)",
  "The siege of Rome by the Ostrogoths under King Theodoric, depicting the desperation within the walls and the relentless assault from outside (early 6th century AD)",
  "Emperor Justinian envisioning the Hagia Sophia, a moment of inspiration, with architects and scholars around, amidst the backdrop of a nascent Byzantium (532-537 AD)",
  "The courtroom drama of the trial of Belisarius, Justinian's general, falsely accused of corruption, a scene filled with tension and betrayal (early 6th century AD)",
  "The Nika Riots in Constantinople, capturing the chaos and violence in the Hippodrome, with Emperor Justinian and Empress Theodora overlooking the turmoil (532 AD)",
  "The Vandalic War, a dynamic scene showing the Roman fleet under General Belisarius sailing towards Carthage to confront the Vandals (533 AD)",
  "The Lombards invading Italy, a scene filled with movement and the clash of cultures, as they pour over the Alps and into the plains of Northern Italy (568 AD)",
  "The codification of the Corpus Juris Civilis by Justinian, depicted as a scholarly endeavor, with scribes, jurists, and the Emperor engaged in deep study and discussion (529-534 AD)",
  "Emperor Honorius, akin to King Solomon in his court, is depicted receiving the grave news of the sack of Rome, surrounded by counselors in a scene reminiscent of the Judgment of Solomon (410 AD)",
  "The encounter between Attila the Hun and Pope Leo I, mirroring the meeting of Alexander the Great and the High Priest of Jerusalem, with Attila on horseback and the Pope exuding calm wisdom (452 AD)",
  "Romulus Augustulus's abdication to Odoacer, evocative of Isaac blessing Jacob, capturing a moment of generational and power shift with a somber atmosphere (476 AD)",
  "The siege of Rome by the Ostrogoths, portrayed in a style reminiscent of the Siege of Troy, highlighting the desperation within Rome and the determination of the besiegers (early 6th century AD)",
  "Emperor Justinian envisioning the Hagia Sophia, portrayed like Daedalus planning the Labyrinth, surrounded by architects and scholars in a scene of creative genesis (532-537 AD)",
  "The trial of Belisarius, framed in the manner of Christ before Pilate, capturing a moment of grave injustice and palpable tension in the courtroom (early 6th century AD)",
  "The Nika Riots, depicted as a chaotic and violent scene akin to the Bacchanalia, with Emperor Justinian and Empress Theodora overlooking the turmoil (532 AD)",
  "The Vandalic War shown as a sea battle reminiscent of Poseidon stirring the waves, with Belisarius' fleet navigating the tumultuous waters towards Carthage (533 AD)",
  "The Lombard invasion of Italy, illustrated with a sense of the epic migration of Aeneas and his followers, emphasizing the dramatic and transformative nature of their journey over the Alps (568 AD)",
  "The compilation of the Corpus Juris Civilis by Justinian, akin to Moses receiving the Ten Commandments, a scene of legal and divine revelation with scribes and jurists in rapt attention (529-534 AD)",
  "The Battle of Taginae, where Belisarius defeats the Ostrogoths, reminiscent of David's victory over Goliath, capturing the dramatic moment of triumph against overwhelming odds (552 AD)",
  "The reign of Emperor Maurice, portrayed like King Cyrus the Great, wise and just, bringing reforms and a brief resurgence to the beleaguered empire (582-602 AD)",
  "The tragic scene of the Massacre of Thessalonica, evoking the Slaughter of the Innocents, with Emperor Theodosius I in a state of remorseful prayer (390 AD)",
  "Theodoric the Great's rule in Italy, depicted as the reign of Dionysus, a time of cultural flourishing and relative peace, amidst scenes of harvest and abundance (493-526 AD)",
  "The construction of Justinian's fortifications at Dara, akin to the building of the Walls of Jericho, a scene bustling with activity and strategic genius (530s AD)",
  "The usurpation of Phocas, resembling the betrayal of Caesar by Brutus, a moment of treachery and a turning point in the empire's history (602 AD)",
  "The Lombard King Alboin in Italy, portrayed in the spirit of Hercules, with scenes of strength and conquest, symbolizing the establishment of a new order (568-572 AD)",
  "The mysterious plague that struck Justinian's empire, depicted like the Plagues of Egypt, emphasizing the despair and helplessness of the people (541-542 AD)",
  "The religious discord over the 'Three Chapters' controversy, akin to the Council of Olympus, a scene of intense debate among bishops and theologians (6th century AD)",
  "The establishment of the Exarchate of Ravenna, shown as the founding of Athens by Athena, a strategic and political masterstroke creating a new center of power (584 AD)",
  "The Battle of the Catalaunian Plains, with Attila the Hun depicted as a fierce lion in battle, representing his strength and ferocity against the Roman and Visigothic forces (451 AD)",
  "Emperor Justinian, portrayed as an eagle overlooking the empire, symbolizing his vision and imperial power during the reconquest and legal reforms (527-565 AD)",
  "The Gothic siege of Rome, with the Romans represented as a herd of besieged elephants, symbolizing their resilience and enduring strength under pressure (537-538 AD)",
  "Belisarius in the Vandalic War, akin to a cunning fox, outmaneuvering the Vandal forces in North Africa, a testament to his strategic genius (533-534 AD)",
  "The depiction of the Nika Riots as a pack of wolves in chaos, symbolizing the rampant violence and unrest within the empire (532 AD)",
  "Theodoric the Great of the Ostrogoths shown as a noble stag, representing his leadership and the peaceful prosperity under his rule in Italy (493-526 AD)",
  "The plague during Justinian's reign portrayed as a swarm of locusts, devastating the empire and representing the unstoppable spread of the disease (541-542 AD)",
  "The Lombard invasion, depicted as a wave of bears descending from the Alps, symbolizing the ferocity and unstoppable nature of their migration into Italy (568 AD)",
  "The depiction of Emperor Maurice as a wise owl, symbolizing his intellect and efforts to restore stability and wisdom to the governance of the empire (582-602 AD)",
  "The fall of the Western Roman Empire, represented by a fading phoenix, symbolizing the end of an era and the transformation of the ancient world (476 AD)",
];

const handcrafted = [
  "Emperor Severus oppresses the Roman Senate and elevates the Praetorian Guard (197 AD)",
  "The profligate luxury of Elagabalus and marriage to a Vestal Virgin (219 AD)",
  "The tremendous stature the usurper Maximin, overcoming Emperor Alexander Severus (235 AD)",
  "Defeat and death of the two Gordians, father and son, by the usurper Maximin (238 AD)",
  "The defeat and death of Emperor Decius and his son, slain by an arrow, and his father beneath a morass, by the Goths in Maesia (251 AD)",
  "The Gothic Nation increases it's numbers while marching to the Danube, preparing for war against the Roman Empire (251 AD)",
  "The Goths acquire a naval force, and sail the Euxine in floating houses with their woman and children, to attack the Roman Empire (260 AD)",
  "Emperor Gratian, who outrages the Roman public in Scythian hunting garb, is murdered while fleeing the usurper Maximis (383)",
  "The consubstantiality of the Trinity vanquishes Arrianism at the Council of Constantinople, unifying The Father, the Son, and Holy Spirit (381 AD)",
  "The conflagration of the Pagan temples in the provinces, with the Christian mob led by the zeal of many bishops to eradicate pagan daemons (391 AD)",
  "Persecution of the Pagans leads to the worship of relics and the adoption of Polythesistic rituals within The Church (390 AD). The cross is now representative of idolatry and animal sacrafice is practiced on the chrstian altar.",
  "Alaric, King of the Goths, at winter-quarters in Tuscany, maintains discipline of forty thousand liberated Goths who long to avenge the injuries of their cruel servitude under Rome (409 AD)",
  "Emperor Honorius overlooks the plundering of the Italian provinces from the safety of Ravenna, while the Roman Senate is forced to flee to the safety of the Vatican (410 AD)",
  "The Vandals cross Gibraltar to the coast of Africa, allying with the Moors, and sack the city of Carthage (439 AD)",
  "Attila the Hun raises the Sword of Mars to direct his conquering hoard towards Europe amidst a cloud of Persian arrows thwarting his plans to conquer the east (434 AD)",
];

export const captions = [...handcrafted];
